// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProtocolService.Data;

#nullable disable

namespace ProtocolService.Migrations
{
    [DbContext(typeof(ProtocolDbContext))]
    partial class ProtocolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProtocolService.Data.Entities.Protocol", b =>
                {
                    b.Property<Guid>("ProtocolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("UPCOMING");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProtocolId");

                    b.HasIndex(new[] { "CreatedByUserId" }, "IX_Protocols_CreatedBy");

                    b.HasIndex(new[] { "Status" }, "IX_Protocols_Status");

                    b.ToTable("Protocols", (string)null);
                });

            modelBuilder.Entity("ProtocolService.Data.Entities.ProtocolSite", b =>
                {
                    b.Property<Guid>("ProtocolSiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("InvestigatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("ProtocolSiteId");

                    b.HasIndex("InvestigatorUserId");

                    b.HasIndex(new[] { "ProtocolId" }, "IX_ProtocolSites_Protocol");

                    b.HasIndex(new[] { "SiteId" }, "IX_ProtocolSites_Site");

                    b.HasIndex(new[] { "ProtocolId", "SiteId" }, "UQ_ProtocolSites")
                        .IsUnique();

                    b.ToTable("ProtocolSites", (string)null);
                });

            modelBuilder.Entity("ProtocolService.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "RoleName" }, "UQ_Roles_RoleName")
                        .IsUnique();

                    b.ToTable("Roles", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ProtocolService.Data.Entities.Site", b =>
                {
                    b.Property<Guid>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SiteId");

                    b.ToTable("Sites", (string)null);
                });

            modelBuilder.Entity("ProtocolService.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email");

                    b.HasIndex(new[] { "RoleId" }, "IX_Users_RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ProtocolService.Data.Entities.Protocol", b =>
                {
                    b.HasOne("ProtocolService.Data.Entities.User", "CreatedByUser")
                        .WithMany("Protocols")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ProtocolService.Data.Entities.ProtocolSite", b =>
                {
                    b.HasOne("ProtocolService.Data.Entities.User", "InvestigatorUser")
                        .WithMany("ProtocolSites")
                        .HasForeignKey("InvestigatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProtocolService.Data.Entities.Protocol", "Protocol")
                        .WithMany("ProtocolSites")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProtocolService.Data.Entities.Site", "Site")
                        .WithMany("ProtocolSites")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestigatorUser");

                    b.Navigation("Protocol");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("ProtocolService.Data.Entities.User", b =>
                {
                    b.HasOne("ProtocolService.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProtocolService.Data.Entities.Protocol", b =>
                {
                    b.Navigation("ProtocolSites");
                });

            modelBuilder.Entity("ProtocolService.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProtocolService.Data.Entities.Site", b =>
                {
                    b.Navigation("ProtocolSites");
                });

            modelBuilder.Entity("ProtocolService.Data.Entities.User", b =>
                {
                    b.Navigation("ProtocolSites");

                    b.Navigation("Protocols");
                });
#pragma warning restore 612, 618
        }
    }
}
