// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Data;

#nullable disable

namespace NotificationService.Migrations
{
    [DbContext(typeof(ServicesDbContext))]
    [Migration("20260608085922_AddSentByUserId")]
    partial class AddSentByUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Data.Entities.ComplianceReport", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("GeneratedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Metrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("DRAFT");

                    b.HasKey("ReportId")
                        .HasName("PK__Complian__D5BD4805A3292A42");

                    b.HasIndex("GeneratedByUserId");

                    b.HasIndex(new[] { "ProtocolId" }, "IX_ComplianceReports_Protocol");

                    b.ToTable("ComplianceReports");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.KpiReport", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("GeneratedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Metrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProtocolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReportId")
                        .HasName("PK__KpiRepor__D5BD4805CC199C16");

                    b.HasIndex("GeneratedByUserId");

                    b.HasIndex(new[] { "ProtocolId" }, "IX_KpiReports_Protocol");

                    b.ToTable("KpiReports");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.LabResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ResultDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ResultValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ResultId")
                        .HasName("PK__LabResul__9769020843354922");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex(new[] { "SampleId" }, "IX_LabResults_SampleId");

                    b.ToTable("LabResults");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("IN_APP");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("SentByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("UNREAD");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12051C010C");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_Notifications_CreatedAt")
                        .IsDescending();

                    b.HasIndex(new[] { "Status" }, "IX_Notifications_Status");

                    b.HasIndex(new[] { "UserId" }, "IX_Notifications_UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatientStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("PatientId")
                        .HasName("PK__Patients__970EC366D83C3BF7");

                    b.HasIndex(new[] { "PatientStatus" }, "IX_Patients_PatientStatus");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.PatientEnrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("EnrollmentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProtocolSiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__PatientE__7F68771B1F36FD7B");

                    b.HasIndex(new[] { "PatientId" }, "IX_Enrollments_PatientId");

                    b.HasIndex(new[] { "ProtocolSiteId" }, "IX_Enrollments_ProtocolSite");

                    b.HasIndex(new[] { "PatientId", "ProtocolSiteId" }, "UQ_PatientEnrollments")
                        .IsUnique();

                    b.ToTable("PatientEnrollments");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Protocol", b =>
                {
                    b.Property<Guid>("ProtocolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("DRAFT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProtocolId")
                        .HasName("PK__Protocol__C1131817174640D1");

                    b.HasIndex(new[] { "CreatedByUserId" }, "IX_Protocols_CreatedBy");

                    b.HasIndex(new[] { "Status" }, "IX_Protocols_Status");

                    b.ToTable("Protocols");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.ProtocolSite", b =>
                {
                    b.Property<Guid>("ProtocolSiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("InvestigatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("ProtocolSiteId")
                        .HasName("PK__Protocol__E753597F555154B1");

                    b.HasIndex("InvestigatorUserId");

                    b.HasIndex(new[] { "ProtocolId" }, "IX_ProtocolSites_Protocol");

                    b.HasIndex(new[] { "SiteId" }, "IX_ProtocolSites_Site");

                    b.HasIndex(new[] { "ProtocolId", "SiteId" }, "UQ_ProtocolSites")
                        .IsUnique();

                    b.ToTable("ProtocolSites");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1A605CD519");

                    b.HasIndex(new[] { "RoleName" }, "UQ_Roles_RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Sample", b =>
                {
                    b.Property<Guid>("SampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CollectedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CollectedDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("COLLECTED");

                    b.HasKey("SampleId")
                        .HasName("PK__Samples__8B99EC6A1A85838E");

                    b.HasIndex("CollectedByUserId");

                    b.HasIndex(new[] { "CollectedDate" }, "IX_Samples_CollectedDate")
                        .IsDescending();

                    b.HasIndex(new[] { "EnrollmentId" }, "IX_Samples_EnrollmentId");

                    b.HasIndex(new[] { "Status" }, "IX_Samples_Status");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Site", b =>
                {
                    b.Property<Guid>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SiteId")
                        .HasName("PK__Sites__B9DCB96346F61CFD");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C7B24EEA7");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email");

                    b.HasIndex(new[] { "RoleId" }, "IX_Users_RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.UserSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("TokenJti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionId")
                        .HasName("PK__UserSess__C9F4929033B2C9BA");

                    b.HasIndex(new[] { "ExpiresAt" }, "IX_UserSessions_ExpiresAt");

                    b.HasIndex(new[] { "TokenJti" }, "IX_UserSessions_TokenJti");

                    b.HasIndex(new[] { "UserId" }, "IX_UserSessions_UserId");

                    b.HasIndex(new[] { "TokenJti" }, "UQ_UserSessions_TokenJti")
                        .IsUnique();

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Visit", b =>
                {
                    b.Property<Guid>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VisitDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("VisitName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VisitStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("SCHEDULED");

                    b.HasKey("VisitId")
                        .HasName("PK__Visits__4D3AA1DE7B9692C3");

                    b.HasIndex(new[] { "EnrollmentId" }, "IX_Visits_EnrollmentId");

                    b.HasIndex(new[] { "VisitDate" }, "IX_Visits_VisitDate")
                        .IsDescending();

                    b.HasIndex(new[] { "VisitStatus" }, "IX_Visits_VisitStatus");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.ComplianceReport", b =>
                {
                    b.HasOne("NotificationService.Data.Entities.User", "GeneratedByUser")
                        .WithMany("ComplianceReports")
                        .HasForeignKey("GeneratedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ComplianceReports_GeneratedByUserId");

                    b.HasOne("NotificationService.Data.Entities.Protocol", "Protocol")
                        .WithMany("ComplianceReports")
                        .HasForeignKey("ProtocolId")
                        .IsRequired()
                        .HasConstraintName("FK_ComplianceReports_ProtocolId");

                    b.Navigation("GeneratedByUser");

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.KpiReport", b =>
                {
                    b.HasOne("NotificationService.Data.Entities.User", "GeneratedByUser")
                        .WithMany("KpiReports")
                        .HasForeignKey("GeneratedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_KpiReports_GeneratedByUserId");

                    b.HasOne("NotificationService.Data.Entities.Protocol", "Protocol")
                        .WithMany("KpiReports")
                        .HasForeignKey("ProtocolId")
                        .HasConstraintName("FK_KpiReports_ProtocolId");

                    b.Navigation("GeneratedByUser");

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.LabResult", b =>
                {
                    b.HasOne("NotificationService.Data.Entities.User", "RecordedByUser")
                        .WithMany("LabResults")
                        .HasForeignKey("RecordedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_LabResults_RecordedByUserId");

                    b.HasOne("NotificationService.Data.Entities.Sample", "Sample")
                        .WithMany("LabResults")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LabResults_SampleId");

                    b.Navigation("RecordedByUser");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Notification", b =>
                {
                    b.HasOne("NotificationService.Data.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.PatientEnrollment", b =>
                {
                    b.HasOne("NotificationService.Data.Entities.Patient", "Patient")
                        .WithMany("PatientEnrollments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientEnrollments_PatientId");

                    b.HasOne("NotificationService.Data.Entities.ProtocolSite", "ProtocolSite")
                        .WithMany("PatientEnrollments")
                        .HasForeignKey("ProtocolSiteId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientEnrollments_ProtocolSite");

                    b.Navigation("Patient");

                    b.Navigation("ProtocolSite");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Protocol", b =>
                {
                    b.HasOne("NotificationService.Data.Entities.User", "CreatedByUser")
                        .WithMany("Protocols")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Protocols_CreatedByUserId");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.ProtocolSite", b =>
                {
                    b.HasOne("NotificationService.Data.Entities.User", "InvestigatorUser")
                        .WithMany("ProtocolSites")
                        .HasForeignKey("InvestigatorUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ProtocolSites_Investigator");

                    b.HasOne("NotificationService.Data.Entities.Protocol", "Protocol")
                        .WithMany("ProtocolSites")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProtocolSites_ProtocolId");

                    b.HasOne("NotificationService.Data.Entities.Site", "Site")
                        .WithMany("ProtocolSites")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK_ProtocolSites_SiteId");

                    b.Navigation("InvestigatorUser");

                    b.Navigation("Protocol");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Sample", b =>
                {
                    b.HasOne("NotificationService.Data.Entities.User", "CollectedByUser")
                        .WithMany("Samples")
                        .HasForeignKey("CollectedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Samples_CollectedByUserId");

                    b.HasOne("NotificationService.Data.Entities.PatientEnrollment", "Enrollment")
                        .WithMany("Samples")
                        .HasForeignKey("EnrollmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Samples_EnrollmentId");

                    b.Navigation("CollectedByUser");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.User", b =>
                {
                    b.HasOne("NotificationService.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.UserSession", b =>
                {
                    b.HasOne("NotificationService.Data.Entities.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSessions_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Visit", b =>
                {
                    b.HasOne("NotificationService.Data.Entities.PatientEnrollment", "Enrollment")
                        .WithMany("Visits")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Visits_EnrollmentId");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Patient", b =>
                {
                    b.Navigation("PatientEnrollments");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.PatientEnrollment", b =>
                {
                    b.Navigation("Samples");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Protocol", b =>
                {
                    b.Navigation("ComplianceReports");

                    b.Navigation("KpiReports");

                    b.Navigation("ProtocolSites");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.ProtocolSite", b =>
                {
                    b.Navigation("PatientEnrollments");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Sample", b =>
                {
                    b.Navigation("LabResults");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.Site", b =>
                {
                    b.Navigation("ProtocolSites");
                });

            modelBuilder.Entity("NotificationService.Data.Entities.User", b =>
                {
                    b.Navigation("ComplianceReports");

                    b.Navigation("KpiReports");

                    b.Navigation("LabResults");

                    b.Navigation("Notifications");

                    b.Navigation("ProtocolSites");

                    b.Navigation("Protocols");

                    b.Navigation("Samples");

                    b.Navigation("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
